version: '3.9'
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file: ../.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
